#!/bin/sh
set -e
package_name=plymouth-theme-biglinux
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/plymouth/themes/deepin-logo/deepin-logo.plymouth"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/plymouth/themes/deepin-ssd-logo/deepin-ssd-logo.plymouth"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/plymouth/themes/deepin-logo/deepin-logo.plymouth"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/plymouth/themes/deepin-ssd-logo/deepin-ssd-logo.plymouth"
;;
esac
exit 0
