#!/bin/sh
set -e
package_name=plymouth-theme-biglinux
mkdir -p "/usr/share/dpkgdivert/plymouth-theme-biglinux"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/plymouth-theme-biglinux/usrshareplymouththemesdeepin-logodeepin-logo.plymouth" --rename "/usr/share/plymouth/themes/deepin-logo/deepin-logo.plymouth"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/plymouth-theme-biglinux/usrshareplymouththemesdeepin-ssd-logodeepin-ssd-logo.plymouth" --rename "/usr/share/plymouth/themes/deepin-ssd-logo/deepin-ssd-logo.plymouth"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/share/plymouth/themes/deepin-logo/deepin-logo.plymouth")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/plymouth-theme-biglinux/usrshareplymouththemesdeepin-logodeepin-logo.plymouth" --rename "/usr/share/plymouth/themes/deepin-logo/deepin-logo.plymouth"
fi
if [ "$(dpkg-divert --list "/usr/share/plymouth/themes/deepin-ssd-logo/deepin-ssd-logo.plymouth")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/plymouth-theme-biglinux/usrshareplymouththemesdeepin-ssd-logodeepin-ssd-logo.plymouth" --rename "/usr/share/plymouth/themes/deepin-ssd-logo/deepin-ssd-logo.plymouth"
fi
;;
esac
exit 0
